{% set name = "svgelements" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/svgelements-{{ version }}.tar.gz
  sha256: 21ce32f188d7968da07f585d88141c0cd8638049a68813d69c7eb941fa09fad6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - svgelements
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/meerk40t/svgelements
  summary: Svg Elements Parsing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
