{% set name = "svgelements" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/svgelements-{{ version }}.tar.gz
  sha256: b04488f33dff09d5f95969542ded7769c3a5e027135e0e8c7bae1b6f293b101b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - svgelements
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/meerk40t/svgelements
  summary: Svg Elements Parsing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
